$ErrorActionPreference = 'Continue'
Set-Location 'd:\Project\dmmdzz_injector'

# =============================================================================
# build_driver.ps1 - Build the kernel driver (.sys) for both normal and KDU
# manual-map modes.
#
# This script CONSUMES the per-build manifest generated by deploy.ps1
# (build_meta\manifest.json + build_meta\driver_names.h). The manifest supplies
# the random stem (-> .sys/.pdb/.inf filenames, device name, service name) and
# the randomized IOCTL device type / function base / debug tag that are baked
# into the binary via driver_names.h. If the manifest is missing, deploy.ps1
# is invoked in -GenerateManifestOnly mode to create one.
# =============================================================================

$ProjectRoot = 'd:\Project\dmmdzz_injector'
$MetaDir     = Join-Path $ProjectRoot 'build_meta'
$manifestFile = Join-Path $MetaDir 'manifest.json'

# ---------------------------------------------------------------------------
# Ensure manifest exists (deploy.ps1 is the generator/source of truth).
# ---------------------------------------------------------------------------
if (-not (Test-Path $manifestFile)) {
    Write-Host "[!] No manifest found. Generating one via deploy.ps1 -GenerateManifestOnly..." -ForegroundColor Yellow
    & powershell -ExecutionPolicy Bypass -File (Join-Path $ProjectRoot 'deploy.ps1') -GenerateManifestOnly
    if ($LASTEXITCODE -ne 0) { Write-Host "[!] Failed to generate manifest" -ForegroundColor Red; exit 1 }
}
$manifest = Get-Content $manifestFile -Raw | ConvertFrom-Json
$drvStem  = $manifest.stem
Write-Host "[+] Using manifest: stem=$drvStem  dbgTag=$($manifest.dbgTag)" -ForegroundColor Magenta

# ---------------------------------------------------------------------------
# Scramble-PeSignature: randomize PE regions that don't affect loading so each
# build produces a file with a distinct hash (defeats hash-based detection).
#
# Regions touched:
#   1. IMAGE_FILE_HEADER.TimeDateStamp (4 bytes at e_lfanew+8)
#   2. DOS stub padding (0x40 .. e_lfanew) — safe padding ignored by loaders.
# File size is unchanged; only byte values differ between builds.
# Safe for KDU-manually-mapped .sys files (the mapper reads PE sections only).
# ---------------------------------------------------------------------------
function Scramble-PeSignature {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return }
    $bytes = [System.IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -lt 0x40) { return }
    $eLfanew = [BitConverter]::ToInt32($bytes, 0x3C)
    if ($eLfanew -le 0x40 -or ($eLfanew + 24) -ge $bytes.Length) { return }
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    try {
        $ts = New-Object byte[] 4
        $rng.GetBytes($ts)
        [Array]::Copy($ts, 0, $bytes, $eLfanew + 8, 4)
        $stubLen = $eLfanew - 0x40
        if ($stubLen -gt 0) {
            $stub = New-Object byte[] $stubLen
            $rng.GetBytes($stub)
            [Array]::Copy($stub, 0, $bytes, 0x40, $stubLen)
        }
    } finally {
        $rng.Dispose()
    }
    [System.IO.File]::WriteAllBytes($Path, $bytes)
    $hash = (Get-FileHash -Path $Path -Algorithm MD5).Hash
    Write-Host "    [scramble] $([System.IO.Path]::GetFileName($Path)) MD5=$hash" -ForegroundColor DarkGray
}

# Find VS
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { $vswhere = "${env:ProgramFiles}\Microsoft Visual Studio\Installer\vswhere.exe" }
$vsInstall = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath | Select-Object -First 1
$vcvars = Join-Path $vsInstall "VC\Auxiliary\Build\vcvars64.bat"
Write-Host "[+] VS: $vsInstall"

# Find WDK
$wdkRoot = "D:\Windows Kits\10"
$wdkVer = (Get-ChildItem "$wdkRoot\Include" -Directory | Where-Object { Test-Path "$wdkRoot\Include\$($_.Name)\km\ntddk.h" } | Select-Object -Last 1).Name
$kmInc = "$wdkRoot\Include\$wdkVer\km"
$kmCrtInc = "$wdkRoot\Include\$wdkVer\km\crt"
$sharedInc = "$wdkRoot\Include\$wdkVer\shared"
$ucrtInc = "$wdkRoot\Include\$wdkVer\ucrt"
$kmLib = "$wdkRoot\Lib\$wdkVer\km\x64"
Write-Host "[+] WDK: $wdkVer"

# Prepare output
$outDir = Join-Path $ProjectRoot 'build_driver'
$objDir = "$outDir\obj"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
New-Item -ItemType Directory -Force -Path $objDir | Out-Null

# ---------------------------------------------------------------------------
# Compile + link. The .sys/.pdb are emitted directly with the stem-based names
# so the PDB path embedded in the PE debug directory is also stem-based (not a
# static "dmmdzz_injector" fingerprint). driver_names.h is pulled from build_meta
# via the include path.
# ---------------------------------------------------------------------------
$tempBat = [System.IO.Path]::GetTempFileName() + ".bat"
$srcDir = Join-Path $ProjectRoot 'driver'
$batContent = @"
@echo off
call "$vcvars" >nul 2>&1
set INCLUDE=
set LIB=
set LIBPATH=

set INCLUDE_ARGS=/I"$kmInc" /I"$kmCrtInc" /I"$sharedInc" /I"$ucrtInc" /I"$srcDir" /I"$MetaDir" /I"$outDir"
set COMPILE_FLAGS=/c /kernel /GS- /Zl /Zi /W3 /WX- /O2 /DNT=1 /D_AMD64_=1 /D_WIN32_WINNT=0x0A00 /utf-8

echo [*] Compiling main.c (normal) ...
cl.exe %COMPILE_FLAGS% %INCLUDE_ARGS% /Fo"$objDir\main.obj" "$srcDir\main.c"
if errorlevel 1 (echo [!] main.c failed & exit /b 1)

echo [*] Compiling main.c [KDU mode] ...
cl.exe %COMPILE_FLAGS% /DDMMDZZ_KDU_MODE %INCLUDE_ARGS% /Fo"$objDir\main_kdu.obj" "$srcDir\main.c"
if errorlevel 1 (echo [!] main.c KDU failed & exit /b 1)

echo [*] Compiling ioctl.c ...
cl.exe %COMPILE_FLAGS% %INCLUDE_ARGS% /Fo"$objDir\ioctl.obj" "$srcDir\ioctl.c"
if errorlevel 1 (echo [!] ioctl.c failed & exit /b 1)

echo [*] Compiling memory.c ...
cl.exe %COMPILE_FLAGS% %INCLUDE_ARGS% /Fo"$objDir\memory.obj" "$srcDir\memory.c"
if errorlevel 1 (echo [!] memory.c failed & exit /b 1)

echo [*] Compiling process.c ...
cl.exe %COMPILE_FLAGS% %INCLUDE_ARGS% /Fo"$objDir\process.obj" "$srcDir\process.c"
if errorlevel 1 (echo [!] process.c failed & exit /b 1)

echo [*] Compiling modules.c ...
cl.exe %COMPILE_FLAGS% %INCLUDE_ARGS% /Fo"$objDir\modules.obj" "$srcDir\modules.c"
if errorlevel 1 (echo [!] modules.c failed & exit /b 1)

echo [*] Compiling ptrscan.c ...
cl.exe %COMPILE_FLAGS% %INCLUDE_ARGS% /Fo"$objDir\ptrscan.obj" "$srcDir\ptrscan.c"
if errorlevel 1 (echo [!] ptrscan.c failed & exit /b 1)

echo [*] Linking normal driver ($drvStem.sys) ...
link.exe /SUBSYSTEM:NATIVE,10.0 /DRIVER /ENTRY:DriverEntry /NODEFAULTLIB /MACHINE:X64 /LIBPATH:"$kmLib" ntoskrnl.lib hal.lib BufferOverflowFastFailK.lib /OUT:"$outDir\$drvStem.sys" /DEBUG /PDB:"$outDir\$drvStem.pdb" $objDir\main.obj $objDir\ioctl.obj $objDir\memory.obj $objDir\process.obj $objDir\modules.obj $objDir\ptrscan.obj
if errorlevel 1 (echo [!] link normal failed & exit /b 1)

echo [*] Linking KDU driver (${drvStem}_kdu.sys) ...
link.exe /SUBSYSTEM:NATIVE,10.0 /DRIVER /ENTRY:DriverEntry /NODEFAULTLIB /MACHINE:X64 /LIBPATH:"$kmLib" ntoskrnl.lib hal.lib BufferOverflowFastFailK.lib /OUT:"$outDir\${drvStem}_kdu.sys" /DEBUG /PDB:"$outDir\${drvStem}_kdu.pdb" $objDir\main_kdu.obj $objDir\ioctl.obj $objDir\memory.obj $objDir\process.obj $objDir\modules.obj $objDir\ptrscan.obj
if errorlevel 1 (echo [!] link kdu failed & exit /b 1)

echo [+] Build complete!
exit /b 0
"@
[System.IO.File]::WriteAllText($tempBat, $batContent, [System.Text.Encoding]::ASCII)

# Run the batch file
$proc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c `"$tempBat`"" -Wait -PassThru -NoNewWindow
Remove-Item $tempBat -ErrorAction SilentlyContinue

if ($proc.ExitCode -ne 0) {
    Write-Host "[!] Build failed with exit code $($proc.ExitCode)"
    exit 1
}

# ---------------------------------------------------------------------------
# Generate INF from template (replace all dmmdzz_injector occurrences with stem).
# ---------------------------------------------------------------------------
$infTemplate = Get-Content "$srcDir\dmmdzz_injector.inf" -Raw
$infContent  = $infTemplate -ireplace 'dmmdzz_injector', $drvStem
Set-Content -Path "$outDir\$drvStem.inf" -Value $infContent -Encoding ASCII

# Save stem for any external tooling that still reads it (harmless).
Set-Content -Path "$outDir\driver_stem.txt" -Value $drvStem -NoNewline

# Randomize PE signature so each build produces a distinct hash.
Scramble-PeSignature -Path "$outDir\$drvStem.sys"
Scramble-PeSignature -Path "$outDir\${drvStem}_kdu.sys"

Write-Host "[+] Driver: $drvStem.sys / ${drvStem}_kdu.sys / $drvStem.inf" -ForegroundColor Magenta

# Show artifacts
Write-Host ""
Write-Host "=== Artifacts ==="
Get-ChildItem "$outDir\*.sys" | Select-Object Name, Length
