# =============================================================================
# deploy.ps1 - Single-entry build coordinator for dmmdzz_injector.
#
# This script is the SOURCE OF TRUTH for the per-build randomization "stem".
# Each run generates a fresh manifest (build_meta\manifest.json) containing a
# random stem plus randomized IOCTL device type / function base / debug tag /
# controller name. The shared header build_meta\driver_names.h is generated
# from the manifest so the kernel driver and the user-mode controller compile
# against identical identifiers (device name, service name, IOCTL codes, debug
# prefix). This makes every build's binary-level fingerprint completely
# different, defeating name/hash/signature-based enumeration.
#
# Flow:
#   1. Generate manifest + driver_names.h   (build_meta\)
#   2. Invoke build_driver.ps1              (consumes manifest)
#   3. Invoke build_usermode.ps1            (consumes manifest)
#   4. Collect all artifacts into deploy\
#
# Usage:
#   # Full pipeline (default):
#   powershell -ExecutionPolicy Bypass -File deploy.ps1
#   powershell -ExecutionPolicy Bypass -File deploy.ps1 -OutDir C:\kdu_test
#
#   # Step-by-step (useful if a stage hangs, e.g. driver linker):
#   powershell -ExecutionPolicy Bypass -File deploy.ps1 -GenerateManifestOnly
#   powershell -ExecutionPolicy Bypass -File deploy.ps1 -BuildDriverOnly
#   powershell -ExecutionPolicy Bypass -File deploy.ps1 -BuildUsermodeOnly
#   powershell -ExecutionPolicy Bypass -File deploy.ps1 -CollectOnly
#
#   # Legacy shortcuts:
#   powershell -ExecutionPolicy Bypass -File deploy.ps1 -SkipBuild   # just collect
# =============================================================================

param(
    [string]$OutDir = "",
    [ValidateSet("Release", "Debug")]
    [string]$Config = "Release",
    # Step-by-step switches (mutually exclusive):
    [switch]$GenerateManifestOnly,
    [switch]$BuildDriverOnly,
    [switch]$BuildUsermodeOnly,
    [switch]$CollectOnly,
    # Legacy:
    [switch]$SkipBuild
)

# Resolve which mode we're in.
$StepMode = "Full"
if ($GenerateManifestOnly) { $StepMode = "Manifest" }
elseif ($BuildDriverOnly)   { $StepMode = "BuildDriver" }
elseif ($BuildUsermodeOnly) { $StepMode = "BuildUsermode" }
elseif ($CollectOnly)       { $StepMode = "Collect" }
elseif ($SkipBuild)         { $StepMode = "Collect" }  # legacy alias

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$KDURoot     = Join-Path $ProjectRoot "KDU-1.4.9\Source"
$MetaDir     = Join-Path $ProjectRoot "build_meta"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Cryptographically-strong random hex string of N bytes (-> 2N hex chars).
function Get-RandomHex {
    param([int]$Bytes = 4)
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $b = New-Object byte[] $Bytes
    try { $rng.GetBytes($b) } finally { $rng.Dispose() }
    return [BitConverter]::ToString($b).Replace("-", "").ToLower()
}

# Build a fresh manifest object with all per-build randomized identifiers.
function New-BuildManifest {
    $stem   = Get-RandomHex 4       # 8-hex: .sys filename, device/service name
    $ctlHex = Get-RandomHex 4       # 8-hex: controller .exe name (independent)
    $dbgHex = Get-RandomHex 3       # 6-hex: debug log tag (independent)
    # IOCTL device type: user-defined range 0x8000..0xFFFF
    $deviceType = Get-Random -Minimum 0x8000 -Maximum 0x10000
    # IOCTL function base: 0x800..0xFF0 (leaves room for +10 codes, <= 0xFFF)
    $funcBase   = Get-Random -Minimum 0x800  -Maximum 0xFF1
    return [ordered]@{
        stem           = $stem
        ioctlDeviceType = $deviceType
        ioctlFuncBase   = $funcBase
        dbgTag          = "[$dbgHex]"
        ctlName         = "svc_$ctlHex.exe"
    }
}

# Emit build_meta\driver_names.h from a manifest so both the driver and the
# user-mode controller include identical randomized identifiers.
function Write-DriverNamesH {
    param([string]$Path, $M)
    $stem  = $M.stem
    $dtHex = '0x{0:X4}' -f [int64]$M.ioctlDeviceType
    $fbHex = '0x{0:X3}' -f [int64]$M.ioctlFuncBase
    $tag   = $M.dbgTag
    $h = @"
#ifndef _DRIVER_NAMES_H_
#define _DRIVER_NAMES_H_
/* Auto-generated by deploy.ps1 - randomized per build, do not edit. */
#define DRIVER_STEM         "$stem"
#define DRIVER_SYS_FILE     L"$stem.sys"
#define DRIVER_SERVICE_NAME "$stem"
#define DEVICE_NAME         L"\\Device\\$stem"
#define DOS_DEVICE_NAME     L"\\??\\$stem"
#define DRIVER_OBJ_NAME     L"\\Driver\\$stem"
#define WIN32_DEVICE_PATH   L"\\\\.\\$stem"
#define DMMDZZ_DEVICE_TYPE      $dtHex
#define DMMDZZ_IOCTL_FUNC_BASE  $fbHex
#define DMMDZZ_DBG_TAG          "$tag"
#endif
"@
    Set-Content -Path $Path -Value $h -Encoding ASCII
}

# Persist manifest to disk (JSON) and regenerate driver_names.h.
function Publish-Manifest {
    param($Manifest)
    New-Item -ItemType Directory -Force -Path $MetaDir | Out-Null
    $manifestFile = Join-Path $MetaDir "manifest.json"
    $Manifest | ConvertTo-Json | Set-Content -Path $manifestFile -Encoding UTF8
    Write-DriverNamesH -Path (Join-Path $MetaDir "driver_names.h") -M $Manifest
    return $manifestFile
}

# ---------------------------------------------------------------------------
# Generate (or load) manifest based on $StepMode
# ---------------------------------------------------------------------------
$manifestFile = Join-Path $MetaDir "manifest.json"

# Manifest-only mode: generate and exit early.
if ($StepMode -eq "Manifest") {
    Write-Host "[+] Step: Generate manifest only" -ForegroundColor Cyan
    $manifest = New-BuildManifest
    Publish-Manifest -Manifest $manifest | Out-Null
    Write-Host "[+] stem=$($manifest.stem)  ctl=$($manifest.ctlName)  dbgTag=$($manifest.dbgTag)" -ForegroundColor Magenta
    Write-Host "[+] IOCTL deviceType=0x$('{0:X4}' -f [int64]$manifest.ioctlDeviceType)  funcBase=0x$('{0:X3}' -f [int64]$manifest.ioctlFuncBase)" -ForegroundColor Magenta
    return
}

# Full mode: regenerate manifest every run (fresh fingerprint per deploy).
if ($StepMode -eq "Full") {
    Write-Host "[+] Step: Regenerating manifest (Full mode)" -ForegroundColor Cyan
    $manifest = New-BuildManifest
    Publish-Manifest -Manifest $manifest | Out-Null
    Write-Host "[+] stem=$($manifest.stem)  ctl=$($manifest.ctlName)  dbgTag=$($manifest.dbgTag)" -ForegroundColor Magenta
    Write-Host "[+] IOCTL deviceType=0x$('{0:X4}' -f [int64]$manifest.ioctlDeviceType)  funcBase=0x$('{0:X3}' -f [int64]$manifest.ioctlFuncBase)" -ForegroundColor Magenta
}
# Step modes (BuildDriver/BuildUsermode/Collect): load existing manifest.
elseif (-not (Test-Path $manifestFile)) {
    Write-Host "[!] No manifest found at $manifestFile" -ForegroundColor Red
    Write-Host "    Run: deploy.ps1 -GenerateManifestOnly" -ForegroundColor Red
    exit 1
} else {
    $manifest = Get-Content $manifestFile -Raw | ConvertFrom-Json
}
$drvStem  = $manifest.stem
$ctlName  = $manifest.ctlName

Write-Host ""
Write-Host "=== dmmdzz_injector - Deploy (StepMode: $StepMode) ===" -ForegroundColor Cyan
Write-Host "  ProjectRoot: $ProjectRoot"
Write-Host "  stem:        $drvStem"
Write-Host "  ctlName:     $ctlName"
Write-Host ""

# ---------------------------------------------------------------------------
# Build phase (skip for Collect mode)
# ---------------------------------------------------------------------------
if ($StepMode -in @("Full", "BuildDriver", "BuildUsermode")) {
    $buildDriver   = Join-Path $ProjectRoot "build_driver.ps1"
    $buildUsermode = Join-Path $ProjectRoot "build_usermode.ps1"

    # Driver build (Full or BuildDriver)
    if ($StepMode -in @("Full", "BuildDriver")) {
        Write-Host "[*] Step: Building kernel driver..." -ForegroundColor Cyan
        & powershell -ExecutionPolicy Bypass -File $buildDriver
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[!] build_driver.ps1 failed (exit $LASTEXITCODE)" -ForegroundColor Red
            exit 1
        }
        Write-Host "[+] Driver build complete" -ForegroundColor Green
        if ($StepMode -eq "BuildDriver") { return }
        Write-Host ""
    }

    # Usermode build (Full or BuildUsermode)
    if ($StepMode -in @("Full", "BuildUsermode")) {
        Write-Host "[*] Step: Building user-mode controller..." -ForegroundColor Cyan
        & powershell -ExecutionPolicy Bypass -File $buildUsermode -Config $Config
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[!] build_usermode.ps1 failed (exit $LASTEXITCODE)" -ForegroundColor Red
            exit 1
        }
        Write-Host "[+] Usermode build complete" -ForegroundColor Green
        if ($StepMode -eq "BuildUsermode") { return }
        Write-Host ""
    }
}

# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------
if ($OutDir -eq "") {
    $OutDir = Join-Path $ProjectRoot "deploy"
}

if (Test-Path $OutDir) {
    # Clean old randomized artifacts from previous deploys (keep KDU files).
    Write-Host "[*] Cleaning old deploy artifacts..." -ForegroundColor Yellow
    Get-ChildItem $OutDir -File | Where-Object {
        ($_.Name -match '^[0-9a-f]{8}(_kdu)?\.(sys|inf|pdb)$') -or
        ($_.Name -match '^svc_[0-9a-f]{8}\.exe$') -or
        ($_.Name -match '^dmmdzz_(ce|injector)') -or
        ($_.Name -match '^dmmdzz_injector(_kdu)?\.(sys|inf|pdb)$')
    } | Remove-Item -Force -ErrorAction SilentlyContinue
} else {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
    Write-Host "[+] Created output directory: $OutDir" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# File collection list
# ---------------------------------------------------------------------------
$files = @(
    @{ Name = "kdu.exe";       Source = Join-Path $KDURoot "Hamakaze\output\x64\Release\kdu.exe";       Desc = "KDU main executable" },
    @{ Name = "drv64.dll";     Source = Join-Path $KDURoot "Tanikaze\output\x64\Release\drv64.dll";     Desc = "KDU provider DLL (Tanikaze)" },
    @{ Name = "Taigei64.dll";  Source = Join-Path $KDURoot "Taigei\output\x64\Release\Taigei64.dll";    Desc = "KDU provider DLL (Taigei)" },
    @{ Name = "kdu.db";        Source = Join-Path $KDURoot "Tanikaze\data\kdu.db";                      Desc = "KDU driver database" },
    @{ Name = "$drvStem.sys";        Source = Join-Path $ProjectRoot "build_driver\$drvStem.sys";        Desc = "Kernel driver (normal/test-sign)" },
    @{ Name = "${drvStem}_kdu.sys";  Source = Join-Path $ProjectRoot "build_driver\${drvStem}_kdu.sys";  Desc = "Kernel driver (KDU manual-map)" },
    @{ Name = "$drvStem.inf";        Source = Join-Path $ProjectRoot "build_driver\$drvStem.inf";        Desc = "Driver INF (PnP install)" },
    @{ Name = "dmmdzz_ce.exe";       Source = Join-Path $ProjectRoot "build_usermode\dmmdzz_ce.exe";     Desc = "CE-style memory scanner" },
    @{ Name = $ctlName;              Source = Join-Path $ProjectRoot "build_usermode\$ctlName";          Desc = "Driver controller + patch utility" }
)

# ---------------------------------------------------------------------------
# Copy files
# ---------------------------------------------------------------------------
$found   = 0
$missing = 0

Write-Host ""
Write-Host "Collecting files..." -ForegroundColor Cyan
Write-Host ""

foreach ($f in $files) {
    $destPath = Join-Path $OutDir $f.Name
    if (Test-Path $f.Source) {
        Copy-Item -Path $f.Source -Destination $destPath -Force
        $sizeKB = [math]::Round((Get-Item $f.Source).Length / 1024, 1)
        Write-Host ("  [+] {0,-25} {1,8} KB  {2}" -f $f.Name, $sizeKB, $f.Desc) -ForegroundColor Green
        $found++
    } else {
        Write-Host ("  [!] {0,-25} MISSING   {1}" -f $f.Name, $f.Desc) -ForegroundColor Red
        Write-Host "      Expected at: $($f.Source)" -ForegroundColor DarkGray
        $missing++
    }
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Deploy Summary" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Output folder: $OutDir"
Write-Host "  stem:          $drvStem"
Write-Host "  ctlName:       $ctlName"
Write-Host "  Found: $found   Missing: $missing"
Write-Host ""

if ($missing -gt 0) {
    Write-Host "  Some files are missing!" -ForegroundColor Yellow
    Write-Host "  Make sure you have built KDU (KDU.sln) before running deploy." -ForegroundColor Yellow
    Write-Host ""
}

if ($missing -eq 0) {
    Write-Host "  All files collected! Next steps:" -ForegroundColor Green
    Write-Host ""
    Write-Host "  1. Open this folder as Administrator CMD:" -ForegroundColor White
    Write-Host "     cd `"$OutDir`"" -ForegroundColor White
    Write-Host ""
    Write-Host "  2. Load driver via KDU (no test signing, no reboot):" -ForegroundColor White
    Write-Host "     kdu.exe -map ${drvStem}_kdu.sys" -ForegroundColor White
    Write-Host "     (the controller auto-runs this if the driver is not loaded)" -ForegroundColor White
    Write-Host ""
    Write-Host "  3. Start target process, then run controller:" -ForegroundColor White
    Write-Host "     $ctlName               (no args = interactive REPL)" -ForegroundColor White
    Write-Host "     $ctlName freecard <game.exe>" -ForegroundColor White
    Write-Host ""
}

# ---------------------------------------------------------------------------
# List final directory
# ---------------------------------------------------------------------------
Write-Host "  Final directory contents:" -ForegroundColor Cyan
Write-Host "  -------------------------------------------"
Get-ChildItem $OutDir -File | ForEach-Object {
    $sizeKB = [math]::Round($_.Length / 1024, 1)
    Write-Host ("  {0,-30} {1,8} KB" -f $_.Name, $sizeKB)
}
Write-Host ""
